stages:
  - fit
    
fit_simple:
  stage: fit
  image: rootproject/root-conda
  script:
    - pwd
    - ls
    - echo $SERVICE_PASS | kinit $CERN_USER@CERN.CH
    - xrdcp root://eospublic.cern.ch//eos/root-eos/HiggsTauTauReduced/GluGluToHToTauTau.root histograms.root
    - mkdir fit_outputs
    - python fit.py histograms.root fit_outputs
  artifacts:
    paths:
    - fit_outputs
    expire_in: 1 week
    

    


